# Minecraft & Forge Versionen (Zentral für alle Mods)
mc_version=1.20.1
forge_version=47.2.0
mappings_channel=official
mappings_version=1.20.1

# Globale Mod-Infos
mod_authors=KarlKarlmann

# ==========================================
# VERSIONEN DER EINZELNEN 150KB-MODS
# ==========================================
version_everyonehashats=1.0.0

# ==========================================
# GROUPS (JAVA PACKAGES) DER MODS
# ==========================================
group_fastdecay=net.kb150.everyonehashats