# Minecraft & Forge Versionen (Zentral für alle Mods)
mc_version=1.20.1
forge_version=47.2.0
mappings_channel=official
mappings_version=1.20.1

# Globale Mod-Infos
mod_authors=KarlKarlmann

# ==========================================
# VERSIONEN DER EINZELNEN 150KB-MODS
# ==========================================
version_dragoncolonies=1.0.2
version_meteorshower=1.0.2
version_everyonehashats=1.0.1
version_survivorcolonies=1.0.0
version_reward_box=1.0.2
version_gridmasternine=1.0.0

# ==========================================
# GROUPS (JAVA PACKAGES) DER MODS
# ==========================================
group_everyonehashats=net.kb150.everyonehashats
group_dragoncolonies=net.kb150.dragoncolonies
group_meteorshower=net.kb150.meteorshower
group_survivorcolonies=net.kb150.survivorcolonies
group_reward_box=net.kb150.reward_box
group_gridmasternine=net.kb150.gridmasternine