modLoader="javafml"
loaderVersion="[47,)"
license="CC BY-NC 4.0"

[[mods]]
modId="reward_box"
version="${version}"
displayName="Reward Box"
displayURL="https://www.n3g.de"
authors="Karl Karlmann"
logoFile="reward_box.png"
description='''
Adds reward boxes by Karl Karlmann
'''

# -------------------------------------------------------------------------
# ABHÄNGIGKEITEN (DEPENDENCIES)
# -------------------------------------------------------------------------

# 1. Forge API
[[dependencies.reward_box]]
modId="forge"
mandatory=true
versionRange="[47.2.0,)"
ordering="NONE"
side="BOTH"

# 2. Minecraft Core
[[dependencies.reward_box]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"