modLoader="javafml"
loaderVersion="[47,)"
license="CC BY-NC 4.0"

[[mods]]
modId="meteorshower"
version="${version}"
displayName="Meteor shower"
displayURL="https://www.n3g.de"
authors="Karl Karlmann"
logoFile="meteorshower.png"
description='''
Triggers a Meteor shower at the start of the map.
'''

# -------------------------------------------------------------------------
# ABHÄNGIGKEITEN (DEPENDENCIES)
# -------------------------------------------------------------------------

# 1. Forge API
[[dependencies.meteorshower]]
modId="forge"
mandatory=true
versionRange="[47.2.0,)"
ordering="NONE"
side="BOTH"

# 2. Minecraft Core
[[dependencies.meteorshower]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"